#!/bin/bash
# cleanup.sh — Elimina tutti i file rigenerabili dal progetto
# Esegui dalla root del progetto: bash cleanup.sh

echo "=== Pulizia file rigenerabili ==="

# 1. Rimuovi le vecchie cartelle modello separate (ora tutto in src/rbergomi/)
echo "Rimuovendo cartelle modello obsolete..."
rm -rf src/blp2017
rm -rf src/mp2018
rm -rf src/hybrid

# 2. LaTeX auxiliary files
echo "Eliminando file ausiliari LaTeX..."
rm -f LaTeX/*.aux LaTeX/*.log LaTeX/*.out LaTeX/*.toc LaTeX/*.synctex.gz
rm -f LaTeX/*.tmp.*
rm -f LaTeX/main.pdf

# 3. Python cache
echo "Eliminando __pycache__..."
find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null

# 4. Log files (verranno ricreati al prossimo avvio)
echo "Eliminando log files..."
rm -f deribit_loader.log
rm -f Results/thesis_pipeline.log

# 5. Cached parquets (verranno ricreati da --index)
echo "Eliminando parquet cached..."
rm -f calibration_results/*.parquet
rm -f data/option_index.parquet

# 6. Calibration results (vecchie + nuove sottocartelle)
echo "Eliminando risultati calibrazione..."
# Vecchie cartelle (pre-ristrutturazione)
rm -rf Results/calibration/figures/rbergomi/*
rm -rf Results/calibration/figures/blp2017/*
rm -rf Results/calibration/figures/hybrid/*
rm -rf Results/calibration/figures/mp2018/*
rm -rf Results/calibration/tables/rbergomi/*
rm -rf Results/calibration/tables/blp2017/*
rm -rf Results/calibration/tables/hybrid/*
rm -rf Results/calibration/tables/mp2018/*
# Nuove cartelle (3 metodi)
rm -rf Results/calibration/figures/cholesky_euler/*
rm -rf Results/calibration/figures/hybrid_euler/*
rm -rf Results/calibration/figures/hybrid_mixed/*
rm -rf Results/calibration/tables/cholesky_euler/*
rm -rf Results/calibration/tables/hybrid_euler/*
rm -rf Results/calibration/tables/hybrid_mixed/*
# Vecchi file nella root (pre-riorganizzazione)
rm -f Results/calibration/figures/*.png
rm -f Results/calibration/tables/*.csv
rm -rf Results/calibration/snapshot_scan/*
rm -rf Results/calibration/snapshot_surfaces/*

# 7. Other generated results
echo "Eliminando altri risultati generati..."
rm -rf Results/fat_tails_kurtosis/figures/*
rm -rf Results/implied_volatility_smile/figures/*
rm -rf Results/implied_volatility_smile/tables/*
rm -rf Results/volatility_term_structure/figures/*
rm -rf Results/volatility_term_structure/tables/*
rm -rf Results/fbm_paths/figures/*
rm -rf Results/fbm_paths/tables/*

# 8. Root figures (generated by iv_visualizer)
echo "Eliminando figure root..."
rm -f figures/*.png figures/*.gif

# 9. Script temporanei
rm -f run_mp2018_hybrid.py

echo ""
echo "=== Pulizia completata ==="
echo "Cartelle rimosse: src/blp2017/, src/mp2018/, src/hybrid/"
echo "I dati raw (data/option/) e il codice sorgente (src/rbergomi/) sono intatti."
echo ""
echo "Prossimi passi:"
echo "  1. python run_all_calibrations.py              # calibrazione completa"
echo "  2. python run_all_calibrations.py --cholesky    # solo Cholesky+Euler"
